### ISSUE TITLE
Domain should not be a required field

### ISSUE THREAD

**Issue by xerosanyam** [dswistowski/surge-sh-action#2]
what if user wants to deploy to a random domain for testing? is it not possible?

**Comment by dswistowski** [comment]
![image](https://user-images.githubusercontent.com/197861/98121309-0a882b80-1ea7-11eb-96af-a7ccc08ae66d.png)

**Comment by xerosanyam** [comment]
Surge itself allows app to be deployed to a random domain. Hence it was just a humble question.

**Comment by dswistowski** [comment]
@xerosanyam 

Surge is generating random domain in cli tool - not on API level. 
You can generate random domain name and just put it to the env variable.

Tools should not implement all possible functionality - but they should be connectable easily with other tools.

If you want random domain - you can use different action to generate a random name and use it as a domain.
Example action to generate random name: https://github.com/marketplace/actions/unique-name-generator-action

```
- uses: TGPSKI/name-generator-node-action@v2
  id: generator
  with:
    separator: '-'
    length: '2'
- name: Deploy to foo-bar.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: '${{ steps.generator.outputs.name }}.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
```
