### ISSUE TITLE
Environment variable as input

### ISSUE THREAD

**Issue by S0lRaK** [dswistowski/surge-sh-action#7]
Is it possible to use an environment variable defined in the workflow step as an input?

```yaml
- name: Publish to surge.sh
        uses: dswistowski/surge-sh-action@v1.0.1
        env:
          SURGE_DOMAIN: https://my-domain.surge.sh
        with:
          # your surge.sh domain to deploy
          domain: env.SURGE_DOMAIN
          # surge.sh login
          login: ${{ secrets.SURGE_LOGIN }}
          # surge.sh token, generate it with `surge token` command
          token: ${{ secrets.SURGE_TOKEN }}
          # your project path
          project: './public/' # optional, default is .
```
